workflows:
  android-apk-build:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_PUBLIC_SUPABASE_URL: "https://ffkrwdvevjuloyxnliga.supabase.co"
        EXPO_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZma3J3ZHZldmp1bG95eG5saWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0NzIxOTgsImV4cCI6MjA5NTA0ODE5OH0.lcUJvWeoHBsK1s3aLyxykqlxk1bIZUr_EBkIxquDRdg"
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Expo Prebuild
        script: |
          npx expo prebuild --platform android --clean --no-install

      - name: Fix Gradle
        script: |
          cd android
          ./gradlew wrapper --gradle-version 8.8 --distribution-type all
          echo "android.defaults.buildfeatures.buildconfig=true" >> gradle.properties
          echo "android.nonTransitiveRClass=false" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError" >> gradle.properties

      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
